# Use default 2026 settings as a base
use_default_settings: true

server:
  secret_key: "69eb32e630b4fa3efd6403428bfb71fc559c99c54433b4239c4569c8a882ca22" # Arbitrary for now
  bind_address: "0.0.0.0"
  port: 8080
  proxies:
    - 127.0.0.1      # Trust localhost
    - 172.16.0.0/12  # Trust Docker default bridge network
    - 172.18.0.0/16  # Trust Docker user-defined bridge network
    - 10.0.0.0/8       # Trust private network (optional)
    - 192.168.0.0/16 # Trust local network (optional)
  real_ip:
    - X-Forwarded-For
    - X-Real-IP

search:
  formats:
    - html
    - json  # Recommended for use with AI apps or APIs
  safe_search: 1

# Optional: Link to a caching service (Valkey is recommended in 2026)
# valkey:
#   url: valkey://valkey:6379/0
